[package]
name = "freeddns-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "5.0"
freeddns-core = { path = "../freeddns-core" }
keyring = { version = "3.0", features = ["apple-native", "windows-native", "linux-native"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
