[package]
name = "simpleddns-app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "SimpleDDNS"
path = "src/main.rs"

[dependencies]
eframe = "0.30"
egui = "0.30"
auto-launch = "0.5"
tray-icon = "0.19"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde_json = "1.0"
simpleddns-core = { version = "0.1.0", path = "../simpleddns-core" }
simpleddns-providers = { version = "0.1.0", path = "../simpleddns-providers" }
simpleddns-storage = { version = "0.1.0", path = "../simpleddns-storage" }
rfd = "0.15"
image = "0.25"
get_if_addrs = "0.5"
windows = { version = "0.58", features = ["Win32_System_Console", "Win32_Foundation"] }

[build-dependencies]
winres = "0.1"
