name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        
    - name: Restore dependencies
      run: dotnet restore SimpleDDNS.sln
      
    - name: Build
      run: dotnet build SimpleDDNS.sln --no-restore -c Release
      
    - name: Test
      run: dotnet test SimpleDDNS.sln --no-build --verbosity normal -c Release
